name = "StataFiles"
uuid = "4250fffb-2d87-4dab-9cf8-12ba0ef8cdb9"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
TableMetadataTools = "9ce81f87-eacc-4366-bf80-b621a3098ee2"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
InlineStrings = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"

[compat]
julia = "1.6"
DataFrames = "1.7.0"
CategoricalArrays = "1.0"
Printf = "1.11"
Dates = "1.11.0"
TableMetadataTools = "0.1.0"
OrderedCollections = "1.8.0"
InlineStrings = "1.4.3"

[extras]

[targets]

